In [97]:
import os
import numpy as np 
import pandas as pd
from sklearn.linear_model import Ridge, RidgeCV, Lasso, LassoCV
from sklearn.metrics import mean_squared_error

In [98]:
X_train = pd.read_csv("data/ancestry_train.data", sep = " ", header=None).values
y_train = pd.read_csv("data/ancestry_train.solution", sep = " ", header=None).values

X_test = pd.read_csv("data/ancestry_test.data", sep = " ", header=None).values

In [99]:
X_train

array([[0, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]])

In [100]:
np.round(y_train, 3)

array([[0.198, 0.75 , 0.052],
       [0.858, 0.142, 0.   ],
       [0.761, 0.237, 0.001],
       ...,
       [0.001, 0.183, 0.817],
       [0.016, 0.591, 0.393],
       [0.   , 0.007, 0.993]])

In [101]:
X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 2, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 2, 1, 1],
       [0, 0, 2, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0]])

In [102]:
#Ridge Regression
model = Ridge(alpha=.001)

model.fit(X_train, y_train)

y_train_pred = model.predict(X_train)
y_test = model.predict(X_test)

train_mse = mean_squared_error(y_train, y_train_pred)

print(train_mse)

0.004798356345573196


In [103]:
#adjust invalid ancestry predictions
for i in y_test:
    for j in range(3):
        if i[j] < 0:
            i[j] = 0
        if i[j] > 1:
            i[j] = 1

# cost function

In [104]:
def cost(y_true, y_hat):
    mse = -np.log10(np.mean((y_true-y_hat)**2)+1e-5)
    return(mse)

# baseline

In [105]:
base = np.ones((y_train.shape[0], y_train.shape[1])) * (1/3)
cost(y_train, base)

0.8401067369385945

In [106]:
y_test
y_test.shape
cost(y_test, base[:10000]) 

0.8811788589334456

# save and zip the file

In [107]:
pd.DataFrame(y_test).to_csv(f"predictions.csv", sep = " ", header = None, index = None)
os.system("zip -r predictions1.zip predictions.csv")

  adding: predictions.csv (deflated 55%)


0